# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import synapse_pb2 as synapse__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synapse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SynapseServiceStub(object):
    """Main Synapse Service with bidirectional streaming for high-throughput agentic workflows
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Build = channel.stream_stream(
                '/synapse.SynapseService/Build',
                request_serializer=synapse__pb2.BuildMessage.SerializeToString,
                response_deserializer=synapse__pb2.BuildMessage.FromString,
                _registered_method=True)
        self.Analyze = channel.stream_stream(
                '/synapse.SynapseService/Analyze',
                request_serializer=synapse__pb2.AnalyzeMessage.SerializeToString,
                response_deserializer=synapse__pb2.AnalyzeMessage.FromString,
                _registered_method=True)
        self.DetectEndpoints = channel.unary_unary(
                '/synapse.SynapseService/DetectEndpoints',
                request_serializer=synapse__pb2.DetectRequest.SerializeToString,
                response_deserializer=synapse__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.TrackEvent = channel.unary_unary(
                '/synapse.SynapseService/TrackEvent',
                request_serializer=synapse__pb2.TrackEventRequest.SerializeToString,
                response_deserializer=synapse__pb2.TrackEventResponse.FromString,
                _registered_method=True)


class SynapseServiceServicer(object):
    """Main Synapse Service with bidirectional streaming for high-throughput agentic workflows
    """

    def Build(self, request_iterator, context):
        """Build MCP server - bidirectional stream for real-time agent communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request_iterator, context):
        """Analyze codebase - bidirectional stream for AI-powered analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectEndpoints(self, request, context):
        """Detect MCP tool candidates - unary RPC, CLI sends all functions, backend AI classifies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackEvent(self, request, context):
        """Track CLI event (init, first_auth) - unary, fire-and-forget telemetry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SynapseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Build': grpc.stream_stream_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=synapse__pb2.BuildMessage.FromString,
                    response_serializer=synapse__pb2.BuildMessage.SerializeToString,
            ),
            'Analyze': grpc.stream_stream_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=synapse__pb2.AnalyzeMessage.FromString,
                    response_serializer=synapse__pb2.AnalyzeMessage.SerializeToString,
            ),
            'DetectEndpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectEndpoints,
                    request_deserializer=synapse__pb2.DetectRequest.FromString,
                    response_serializer=synapse__pb2.DetectResponse.SerializeToString,
            ),
            'TrackEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackEvent,
                    request_deserializer=synapse__pb2.TrackEventRequest.FromString,
                    response_serializer=synapse__pb2.TrackEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.SynapseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.SynapseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SynapseService(object):
    """Main Synapse Service with bidirectional streaming for high-throughput agentic workflows
    """

    @staticmethod
    def Build(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/synapse.SynapseService/Build',
            synapse__pb2.BuildMessage.SerializeToString,
            synapse__pb2.BuildMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/synapse.SynapseService/Analyze',
            synapse__pb2.AnalyzeMessage.SerializeToString,
            synapse__pb2.AnalyzeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectEndpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.SynapseService/DetectEndpoints',
            synapse__pb2.DetectRequest.SerializeToString,
            synapse__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.SynapseService/TrackEvent',
            synapse__pb2.TrackEventRequest.SerializeToString,
            synapse__pb2.TrackEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
